version: "3.1"

services:
  web:
    image: hpbonfim/php-apache:latest
    restart: unless-stopped
    volumes:
    - ./www:/var/www/html
    networks:
      - app-network

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=cadastro
    volumes:
      - db:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
